name: Docker

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # 每天零点触发

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  ALIYUN_REGISTRY_USER: ${{ secrets.ALIYUN_REGISTRY_USER }}
  ALIYUN_REGISTRY_PASSWORD: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
  ALIYUN_HUB_NAME: ${{ secrets.ALIYUN_HUB_NAME }}
  MM_NOTIFY_URL: ${{ secrets.MM_NOTIFY_URL }}
  HEARTCHECK_URL: ${{ secrets.HEARTCHECK_URL }}
  PUSHDEER_URL: ${{ secrets.PUSHDEER_URL }}
  PUSHDEER_API_KEY: ${{ secrets.PUSHDEER_API_KEY }}

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: image=moby/buildkit:latest

    - name: Check out code
      uses: actions/checkout@v2

    - name: Replace USERNAME_PLACEHOLDER
      run: bash replace_username.sh


    - name: Login to Docker registry
      run: echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login -u $ALIYUN_REGISTRY_USER --password-stdin $REGISTRY

    - name: Build and Push Docker Image
      run: |
        while IFS= read -r line; do
          image=$(echo $line | awk '{print $1}')
          tag=$(echo $line | awk '{print $2}')
          docker buildx build --platform linux/amd64,linux/arm64 -t $REGISTRY/$ALIYUN_HUB_NAME/$tag --push .
        done < trigger.txt

    - name: Send notification
      run: |
        data=$(cat trigger.txt)
        curl -X POST $PUSHDEER_URL \
             -d "pushkey=$PUSHDEER_API_KEY" \
             -d "text=镜像同步成功！"

    - name: Send Heartcheck
      run: curl -X GET $HEARTCHECK_URL
